version: '3.3'
services:
  ldes-mongodb:
    container_name: ${USECASE_NAME:-ldes-server-snapshot}_ldes-mongodb
    image: mongo:${MONGODB_TAG:-6.0.4}
    ports:
      - ${MONGODB_PORT:-27017}:27017
    networks:
      - ldes
  ldes-server:
    container_name: ${USECASE_NAME:-ldes-server-snapshot}_ldes-server
    image: ghcr.io/informatievlaanderen/ldes-server:${LDES_SERVER_TAG:-20230407t0803}
    environment:
      - MONGOCK_MIGRATIONSCANPACKAGE_0=be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.mongock.changeset1
      - MONGOCK_MIGRATIONSCANPACKAGE_1=be.vlaanderen.informatievlaanderen.ldes.server.infra.mongo.mongock.changeset2
      - MANAGEMENT_TRACING_ENABLED=False
      - SIS_DATA=/tmp
      - SPRING_DATA_MONGODB_URI=mongodb://ldes-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=test
      - LDES_HOSTNAME=http://localhost:8080
      - LDES_COLLECTIONNAME=mobility-hindrances
      - LDES_TIMESTAMPPATH=http://www.w3.org/ns/prov#generatedAtTime
      - LDES_VERSIONOF=http://purl.org/dc/terms/isVersionOf
      - LDES_MEMBERTYPE=https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder
      - DEFAULT_VIEW=true
    volumes:
      - ../../data/epsg:/tmp/Databases:rw
    ports:
      - 8080:8080
    networks:
      ldes:
        aliases:
          - ldes-server
    depends_on:
      - ldes-mongodb

networks:
  ldes:
    name: ${USECASE_NAME:-ldes-server-snapshot}_network
