version: '3.3'
services:
  ldes-server-simulator:
    container_name: ${USECASE_NAME:-simulator-workflow-server-mongo}_ldes-server-simulator
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-server-simulator:${LDES_SERVER_SIMULATOR_TAG:-20221220t0725}
    environment:
      - BASEURL=http://ldes-server-simulator
      - SEED=/tmp/data
    ports:
      - ${LDES_SERVER_SIMULATOR_PORT:-9011}:80
    volumes:
      - type: bind
        source: ../../../../ldes-server-simulator/data/empty
        target: /tmp/data
    networks:
      - ldes
  nifi-workflow:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-workbench-nifi:${LDES_WORKBENCH_NIFI_TAG:-20221216t155826}
    container_name: ${USECASE_NAME:-simulator-workflow-server-mongo}_ldes-workbench-nifi
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    ports:
      - ${NIFI_UI_PORT:-8443}:8443
    networks:
      - ldes
  ldes-server:
    container_name: ${USECASE_NAME:-simulator-workflow-server-mongo}_ldes-server
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-server:${LDES_SERVER_TAG:-20221216t1458}
    environment:
      - SIS_DATA=/tmp
      - SPRING_DATA_MONGODB_DATABASE=gipod
      - LDES_COLLECTIONNAME=mobility-hindrances
      - LDES_MEMBERTYPE=https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder
      - SPRING_DATA_MONGODB_HOST=ldes-mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - LDES_HOSTNAME=http://localhost:${LDES_SERVER_PORT:-8080}
      - LDES_SHAPE=https://private-api.gipod.test-vlaanderen.be/api/v1/ldes/mobility-hindrances/shape
      - VIEW_TIMESTAMPPATH=http://www.w3.org/ns/prov#generatedAtTime
      - VIEW_VERSIONOFPATH=http://purl.org/dc/terms/isVersionOf
      # STRATEGY: both geospatial and timebased
      - VIEWS_0_NAME=mobility-hindrances-by-location-and-time
      - VIEWS_0_FRAGMENTATIONS_0_NAME=geospatial
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_MAXZOOMLEVEL=${VIEWS_0_FRAGMENTATIONS_0_CONFIG_MAXZOOMLEVEL:-15}
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_PROJECTION=lambert72
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_FRAGMENTERPROPERTY=http://www.opengis.net/ont/geosparql#asWKT
      - VIEWS_0_FRAGMENTATIONS_1_NAME=timebased
      - VIEWS_0_FRAGMENTATIONS_1_CONFIG_MEMBERLIMIT=${VIEWS_0_FRAGMENTATIONS_1_CONFIG_MEMBERLIMIT:-5}
      # # ALTERNATIVE STRATEGY: only timebased
      # - VIEWS_0_NAME=mobility-hindrances-by-time
      # - VIEWS_0_FRAGMENTATIONS_0_NAME=timebased
      # - VIEWS_0_FRAGMENTATIONS_0_CONFIG_MEMBERLIMIT=${VIEWS_0_FRAGMENTATIONS_0_CONFIG_MEMBERLIMIT:-5}
      # # ALTERNATIVE STRATEGY: only geospatial
      # - VIEWS_0_NAME=mobility-hindrances-by-location
      # - VIEWS_0_FRAGMENTATIONS_0_NAME=geospatial
      # - VIEWS_0_FRAGMENTATIONS_0_CONFIG_MAXZOOMLEVEL=${VIEWS_0_FRAGMENTATIONS_0_CONFIG_MAXZOOMLEVEL:-15}
      # - VIEWS_0_FRAGMENTATIONS_0_CONFIG_PROJECTION=lambert72
      # - VIEWS_0_FRAGMENTATIONS_0_CONFIG_FRAGMENTERPROPERTY=http://www.opengis.net/ont/geosparql#asWKT
    ports:
      - ${LDES_SERVER_PORT:-8080}:8080
    networks:
      - ldes
    depends_on:
      - ldes-mongodb
  ldes-mongodb:
    container_name: ${USECASE_NAME:-simulator-workflow-server-mongo}_ldes-mongodb
    image: mongo:${MONGODB_TAG:-6.0.3}
    ports:
      - ${MONGODB_PORT:-27017}:27017
    volumes:
      - type: bind
        source: ${MONGODB_DATA_FOLDER}
        target: /data/db
    networks:
      - ldes
networks:
  ldes:
    name: ${USECASE_NAME:-simulator-workflow-server-mongo}_network
