version: '3.3'
services:
  ldes-server:
    env_file:
      - ./ldes-server/config.local.env
    image: ghcr.io/informatievlaanderen/ldes-server:20220704T1516
    container_name: ldes-server
    ports:
      - "8080:8080"
    networks:
      - ldes
    depends_on:
      - ldes-mongodb
  ldes-mongodb:
    image: mongo
    container_name: ldes-mongodb
    ports:
      - 27017:27017
    restart: always
    networks:
      - ldes
  gipod-server-simulator:
    image: ghcr.io/informatievlaanderen/ldes-server-simulator:20220629t1521
    container_name: gipod-server-simulator
    ports:
      - "9011:80"
    environment:
      - BASEURL=http://gipod-server-simulator
    networks:
      - ldes
  replicate-workflow:
    image: vsds/ldes-client-workflow
    container_name: replicate-workflow
    build:
      context: ./replicate-workflow
      args:
        PAT_READ_PACKAGES: ${PAT_READ_PACKAGES}
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    ports:
      - "8443:8443"
    #   - "9002:8080"
    # volumes:
    #   - ./nifi/logs:/opt/nifi/nifi-current/logs
    #   - ./nifi/conf:/opt/nifi/nifi-current/conf
    networks:
      - ldes
networks:
  ldes: {}
