@startuml "LDES server demo - container diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title LDES server demo - container diagram

Person(tester, "Tester")

System_Ext(simulator, "GIPOD simulator", "Simple LDES fragment server (alternative for GIPOD LDES server which contains too much data)")
System_Ext(workflow, "LDES server demo", "Workflow containing LDES client processor")

System_Boundary(server_host, "LDES server"){
    Container(server, "LDES server", "Java", "LDES server ingesting members and offering an endpoint for consumption")
    Container_Ext(database, "Storage", "MongoDB", "Contains LDES members and fragments")
}

Rel_D(tester, simulator, "view GIPOD fragments", "HTTP")
Rel_D(tester, workflow, "create and run workflow", "HTTPS")
Rel_D(tester, server, "verify GIPOD data set replicated", "HTTP")
Rel_L(workflow, simulator, "retrieves and follows LDES fragments", "HTTP (method GET)")
Rel_R(workflow, server, "pushes LDES members", "HTTP (method POST)")
Rel_R(server, database, "stores and retrieves LDES members", "HTTP")

@enduml