@startuml "LDES server demo - context diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title LDES server demo - context diagram

Person(tester, "Tester")

System_Ext(client, "LDES server demo")
System_Ext(simulator, "GIPOD simulator", "Simple LDES fragment server (alternative for GIPOD LDES server which contains too much data)")
System(server, "LDES server", "LDES server ingesting members and offering an endpoint for consumption")

Rel_L(client, simulator, "retrieves and follows LDES fragments", "HTTP (method GET)")
Rel_R(client, server, "pushes LDES members", "HTTP (method POST)")
Rel_D(tester, simulator, "view GIPOD fragments", "HTTP")
Rel_D(tester, server, "verify GIPOD data set replicated", "HTTP")
Rel_D(tester, client, "create and run workflow", "HTTPS")

@enduml