server:
  port: 8080
orchestrator:
  pipelines:
    - name: simulator-to-server-pipeline
      description: "This pipeline uses an LDES client to read an existing LDES and send the members as N-Quads to a LDES Server"
      input:
        name: be.vlaanderen.informatievlaanderen.ldes.ldi.client.LdioLdesClient
        config:
          url: http://nginx:8080/api/v1/ldes/mobility-hindrances
          auth:
            type: OAUTH2_CLIENT_CREDENTIALS
            client-id: clientId
            client-secret: secret
            token-endpoint: http://mock-oauth2-server:8080/default/token
        adapter:
          name: be.vlaanderen.informatievlaanderen.ldes.ldi.RdfAdapter
      outputs:
        - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
          config:
            endpoint: http://ldes-server:8080/mobility-hindrances
            content-type: application/n-quads
