@startuml "LDES Server Demo - Context Diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title LDES Server Demo - Context Diagram

Person(tester, "Tester")

System_Ext(client, "LDES Workflow")
System_Ext(simulator, "LDES Server Simulator", "Simple LDES fragment server")
System(server, "LDES Server", "LDES Server ingesting members and offering an endpoint for consumption")

Rel_L(client, simulator, "retrieves and follows LDES fragments", "HTTP (method GET)")
Rel_R(client, server, "pushes LDES members", "HTTP (method POST)")
Rel_D(tester, simulator, "view LDES fragments", "HTTP")
Rel_D(tester, server, "verify LDES data set replicated", "HTTP")
Rel_D(tester, client, "create and run workflow", "HTTPS")

@enduml