@startuml "LDES IoW Use Case Demo - Context Diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title LDES IoW Use Case Demo - Context Diagram

Person(tester, "Tester")

System_Ext(generator, "JSON Data Generator", "Simple generator creating\n**WaterQualityObserved** updates (NGSI-v2 format)")
System(nifi, "Apache NiFi system","Contains\n**IoW Workflow**")
System_Ext(servers, "LDES Servers", "collection of LDES Servers ingesting & serving:\n**Devices**\n**DeviceModels**\n**WaterQualityObserved**")
System_Ext(database, "Storage", "MongoDB - Contains LDES members and fragments")

Rel_R(generator, nifi, "generates and pushes NGSI-v2 updates", "HTTP (method POST)")
Rel_D(tester, nifi, "create and run workflow", "HTTPS")
Rel_D(tester, nifi, "pushes Devices & DeviceModels", "HTTPS")
Rel_D(tester, servers, "verifies all LDES's are correct & fragmented time-based", "HTTP")
Rel_R(nifi, servers, "pushes LDES members", "HTTP (method POST)")
Rel_R(servers, database, "stores and retrieves LDES members", "mongo")

@enduml