services:

  nifi-workflow:
    image: ghcr.io/informatievlaanderen/ldi-workbench-nifi:${LDI_WORKBENCH_NIFI_TAG:-latest}
    container_name: ${USECASE_NAME:-rdf4j-repository-materialisation}-ldi-workbench-nifi
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_UI_PORT:-8000}
    ports:
      - ${NIFI_UI_PORT:-8000}:${NIFI_UI_PORT:-8000}
    networks:
      - ldes
    volumes:
      - "./nifi:/home/nifi/data"
      
  rdf4j-server:
    image: eclipse/rdf4j-workbench:${RDF4J_SERVER_TAG:-4.2.2}
    container_name: ${USECASE_NAME:-rdf4j-repository-materialisation}-rdf4j-server
    environment:
      - "JAVA_OPTS=-Xms1g -Xmx4g"
    ports:
      - 8080:8080
    networks:
      - ldes
      
networks:
  ldes:
    name: ${USECASE_NAME:-rdf4j-repository-put}_network
