@startuml "LDES client demo - container diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title LDES client demo - container diagram

Person(tester, "Tester")

System_Ext(simulator, "GIPOD simulator", "Simple LDES fragment server (alternative for GIPOD LDES server which contains too much data)")
System_Ext(sink, "LDES members sink", "Little HTTP server accepting LDES members from the LDES client")

System_Boundary(workflow_system, "LDES client Demo"){
    Container(workflow, "LDES client workflow", "Apache Nifi", "Workflow containing LDES client processor")
}

Rel_D(tester, simulator, "view GIPOD fragments", "HTTP")
Rel_D(tester, workflow, "create and run workflow", "HTTPS")
Rel_D(tester, sink, "verify GIPOD data set replicated", "HTTP")
Rel_L(workflow, simulator, "retrieves and follows LDES fragments", "HTTP (method GET)")
Rel_R(workflow, sink, "pushes LDES members", "HTTP (method POST)")

@enduml