server:
  port: 8080
orchestrator:
  input:
    name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpIn
    adapter:
      name: "be.vlaanderen.informatievlaanderen.ldes.ldi.NgsiV2ToLdAdapter"
      config:
        coreContext: "https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"
  transformers:
    - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator
      config:
        member-type: https://uri.etsi.org/ngsi-ld/default-context/Device
        delimiter: "/"
        # date-observed-property: "" # should be a property path:
        # "[<https://uri.etsi.org/ngsi-ld/default-context/dateLastValueReported> <https://uri.etsi.org/ngsi-ld/hasValue>]"
        generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
        versionOf-property: http://purl.org/dc/terms/isVersionOf
  outputs:
    - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
      config:
        endpoint: http://ldes-server-devices:8080/devices
        content-type: application/n-quads
