services:
  ldes-client-sink:
    image: vsds/ldes-client-sink
    build:
      context: ../../ldes-client-sink
    ports:
      - "9003:80"
    networks:
      - e2e-test
  replicate-workflow:
    container_name: replicate-workflow-20220524-demo1
    build:
      context: ./replicate-workflow
      args:
        PAT_READ_PACKAGES: ${PAT_READ_PACKAGES}
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    ports:
      - "8443:8443"
    networks:
      - e2e-test
  ldes-server-simulator:
    image: vsds/ldes-server-simulator
    build:
      context: ../../ldes-server-simulator
    ports:
      - "9001:80"
    environment:
      - BASEURL=http://ldes-server-simulator
      - SEED=/tmp/gipod-data
    volumes:
      - type: bind
        source: ../../ldes-server-simulator/data/gipod
        target: /tmp/gipod-data
    networks:
      - e2e-test

networks:
  e2e-test: {}
