version: '3.3'
services:
  ldes-client-sink:
    image: vsds/ldes-client-sink
    container_name: ${USECASE_NAME:-sink-mongo}_ldes-client-sink
    build:
      context: .
      args:
        - CONNECTION_URI=mongodb://ldes-mongodb:27017
    ports:
      - ${LDES_CLIENT_SINK_PORT}:80
    networks:
      - ldes
  ldes-mongodb:
    image: mongo:${MONGODB_TAG:-6.0.3}
    container_name: ${USECASE_NAME:-sink-mongo}_ldes-mongodb
    ports:
      - ${MONGODB_PORT}:27017
    networks:
      - ldes
networks:
  ldes: {}
