@startuml "LDES client demo - context diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

title LDES client demo - context diagram

Person(tester, "Tester")

System(client, "LDES client Demo")
System_Ext(simulator, "LDES server simulator", "Simple LDES fragment server")
System_Ext(sink, "LDES members sink", "Little HTTP server accepting LDES members from the LDES client")

Rel_L(client, simulator, "retrieves and follows LDES fragments", "HTTP (method GET)")
Rel_R(client, sink, "pushes LDES members", "HTTP (method POST)")
Rel_D(tester, simulator, "view LDES fragments", "HTTP")
Rel_D(tester, sink, "verify LDES data set replicated", "HTTP")
Rel_D(tester, client, "create and run workflow", "HTTPS")

@enduml