services:
  ldes-server-simulator:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-server-simulator:${LDES_SERVER_SIMULATOR_TAG:-20230214t1503}
    container_name: ${USECASE_NAME:-persisted-state}_ldes-server-simulator
    environment:
      - BASEURL=http://ldes-server-simulator
    ports:
      - ${LDES_SERVER_SIMULATOR_PORT:-9011}:80
    networks:
      - ldes
  nifi-workflow:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-workbench-nifi:${LDES_WORKBENCH_NIFI_TAG:-20230214t123440}
    container_name: ${USECASE_NAME:-persisted-state}_ldes-workbench-nifi
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_UI_PORT:-8000}
    ports:
      - ${NIFI_UI_PORT:-8000}:8000
    networks:
      - ldes
  ldes-client-sink:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-client-sink:${LDES_CLIENT_SINK_TAG:-20230214t1503}
    container_name: ${USECASE_NAME:-persisted-state}_ldes-client-sink
    environment:
      - MEMORY=true
      - COLLECTION_NAME=${LDES_CLIENT_SINK_COLLECTION_NAME:-mobility-hindrances}
      - MEMBER_TYPE=${LDES_CLIENT_SINK_MEMBER_TYPE:-https://data.vlaanderen.be/ns/mobiliteit#Mobiliteitshinder}
    ports:
      - ${LDES_CLIENT_SINK_PORT:-9003}:80
    networks:
      - ldes
networks:
  ldes:
    name: ${USECASE_NAME:-persisted-state}_network
