@startuml "LDES Client Demo - Container Diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title LDES Client Demo - Container Diagram

Person(tester, "Tester")

System_Ext(simulator, "LDES Server Simulator", "Simple LDES fragment server")
System_Ext(sink, "LDES Client Sink", "Little HTTP server accepting LDES members from the LDES client")

System_Boundary(workflow_system, "LDES Workflow"){
    Container(workflow, "LDES Client Workflow", "Apache Nifi", "Workflow containing LDES client processor")
}

Rel_D(tester, simulator, "view LDES fragments", "HTTP")
Rel_D(tester, workflow, "create and run workflow", "HTTPS")
Rel_D(tester, sink, "verify LDES data set replicated", "HTTP")
Rel_L(workflow, simulator, "retrieves and follows LDES fragments", "HTTP (method GET)")
Rel_R(workflow, sink, "pushes LDES members", "HTTP (method POST)")

@enduml