version: '3.3'
services:
  gtfs2ldes-js:
    container_name: ${USECASE_NAME:-gtfs-geo-fragment}_gtfs2ldes-js
    image: ghcr.io/julianrojas87/gtfs2ldes-js:${GTFS2LDES_TAG:-20230129t1743}
    profiles:
      - delayed-started
    environment:
      - NODE_OPTIONS=${NODE_OPTIONS:-}
      - GTFS_SOURCE=${GTFS_SOURCE}
      - GTFSRT_SOURCE=${GTFSRT_SOURCE}
      - BASE_IRI=${GTFS_BASE_IRI}
      - TARGET_URL=http://nifi-workflow:9005/gtfs
      - GTFS_CRON=${GTFS_CRON:-0 0 3 1 * *}
      - GTFSRT_CRON=${GTFSRT_CRON:-*/30 * * * * *}
      - RUN_ON_LAUNCH=${RUN_ON_LAUNCH:-true}
      - THROTTLE_RATE=${THROTTLE_RATE:-10}
      - AUTH_HEADER=${AUTH_HEADER:-X-API-KEY}
      - AUTH_HEADER_VALUE=${AUTH_HEADER_VALUE:-}
    volumes:
      - type: bind
        source: ${GTFS2LDES_DATA_FOLDER}
        target: /data
    networks:
      - ldes
  nifi-workflow:
    container_name: ${USECASE_NAME:-gtfs-geo-fragment}_nifi-workflow
    image: ${DOCKER_REPO:-docker.io}/apache/nifi:${NIFI_TAG:-1.19.1}
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
      - NIFI_JVM_HEAP_INIT=${NIFI_JVM_HEAP_INIT:-2g}
      - NIFI_JVM_HEAP_MAX=${NIFI_JVM_HEAP_MAX:-4g}
    ports:
      - ${NIFI_UI_PORT:-8443}:8443
      - ${NIFI_WORKFLOW_LISTEN_PORT:-9005}:9005
    # volumes:
    #   - type: bind
    #     source: ${NIFI_BASE_FOLDER}/content_repository
    #     target: /opt/nifi/nifi-current/content_repository
    #   - type: bind
    #     source: ${NIFI_BASE_FOLDER}/database_repository
    #     target: /opt/nifi/nifi-current/database_repository
    #   - type: bind
    #     source: ${NIFI_BASE_FOLDER}/flowfile_repository
    #     target: /opt/nifi/nifi-current/flowfile_repository
    #   - type: bind
    #     source: ${NIFI_BASE_FOLDER}/provenance_repository
    #     target: /opt/nifi/nifi-current/provenance_repository
    networks:
      - ldes
  ldes-server:
    container_name: ${USECASE_NAME:-gtfs-geo-fragment}_ldes-server
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-server:${LDES_SERVER_TAG:-20230131t0819}
    environment:
      - SIS_DATA=/tmp
      - SPRING_DATA_MONGODB_DATABASE=${SPRING_DATA_MONGODB_DATABASE}
      - SPRING_DATA_MONGODB_HOST=ldes-mongodb
      - SPRING_DATA_MONGODB_PORT=27017
      - LDES_HOSTNAME=http://localhost:${LDES_SERVER_PORT:-8080}
      - LDES_COLLECTIONNAME=${LDES_COLLECTIONNAME:-connections}
      - LDES_MEMBERTYPE=${LDES_MEMBERTYPE:-http://semweb.mmlab.be/ns/linkedconnections#Connection}
      - LDES_SHAPE=${LDES_SHAPE:-}
      - VIEW_TIMESTAMPPATH=${VIEW_TIMESTAMPPATH:-http://www.w3.org/ns/prov#generatedAtTime}
      - VIEW_VERSIONOFPATH=${VIEW_VERSIONOFPATH:-http://purl.org/dc/terms/isVersionOf}
      - VIEWS_0_NAME=${VIEWS_0_NAME:-by-location-and-time}
      - VIEWS_0_FRAGMENTATIONS_0_NAME=geospatial
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_PROJECTION=noop
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_MAXZOOMLEVEL=${VIEWS_0_FRAGMENTATIONS_0_CONFIG_MAXZOOMLEVEL:-15}
      - VIEWS_0_FRAGMENTATIONS_0_CONFIG_FRAGMENTERPROPERTY=http://www.opengis.net/ont/geosparql#asWKT
      - VIEWS_0_FRAGMENTATIONS_1_NAME=timebased
      - VIEWS_0_FRAGMENTATIONS_1_CONFIG_MEMBERLIMIT=${VIEWS_0_FRAGMENTATIONS_1_CONFIG_MEMBERLIMIT:-100}
      # - VIEWS_1_NAME=${VIEWS_1_NAME:-by-time}
      # - VIEWS_1_FRAGMENTATIONS_0_NAME=timebased
      # - VIEWS_1_FRAGMENTATIONS_0_CONFIG_MEMBERLIMIT=${VIEWS_1_FRAGMENTATIONS_0_CONFIG_MEMBERLIMIT:-250}
    ports:
      - ${LDES_SERVER_PORT:-8080}:8080
    networks:
      - ldes
    depends_on:
      - ldes-mongodb
  ldes-mongodb:
    container_name: ${USECASE_NAME:-gtfs-geo-fragment}_ldes-mongodb
    image: mongo:${MONGODB_TAG:-6.0.3}
    ports:
      - ${MONGODB_PORT:-27017}:27017
    volumes:
      - type: bind
        source: ${MONGODB_DATA_FOLDER}
        target: /data/db
    networks:
      - ldes
networks:
  ldes:
    name: ${USECASE_NAME:-gtfs-geo-fragment}_network
