springdoc:
  swagger-ui:
    path: /v1/swagger
ldes-server:
  host-name: "http://localhost:8080"
spring:
  data:
    mongodb:
      host: ldes-mongodb
      port: 27017
      database: ldes
      auto-index-creation: true