@startuml "IoW Use Case - Component Diagram"
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title IoW Use Case - Component Diagram

Person(tester, "Tester")

System_Ext(generator, "JSON Data Generator", "Simple generator creating\n**WaterQualityObserved** updates (NGSI-v2 format)")

System_Boundary(pipeline_d, "Devices Pipeline") {
    Container_Boundary(workflow_devices, "IoW Workflow - Devices", "LDI Orchestrator", "Workflow containing standard and custom LDIO components"){
         Component(ldi_d, "HTTP in", "Java - **custom** LDI HTTP in", "Receives NGSI-LD state object")
         Component(translator_d, "NGSI v2 to LD translation", "Java - **custom** LDI translator", "Translates NGSI-v2 to NGSI-LD according to Fiware rules")
         Component(creator_d, "LDES member creator", "Java - **custom** LDI translator", "Produces LDES member (version object) from NGSI-LD")
         Component(ldo_d, "HTTP out", "Java - **custom** LDI HTTP out", "Sends LDES member (version object)")
    }
}
System_Boundary(pipeline_m, "Models Pipeline") {
    Container_Boundary(workflow_models, "IoW Workflow - Models", "LDI Orchestrator", "Workflow containing standard and custom LDIO components"){
         Component(ldi_m, "HTTP in", "Java - **custom** LDI HTTP in", "Receives NGSI-LD state object")
         Component(translator_m, "NGSI v2 to LD translation", "Java - **custom** LDI translator", "Translates NGSI-v2 to NGSI-LD according to Fiware rules")
         Component(creator_m, "LDES member creator", "Java - **custom** LDI translator", "Produces LDES member (version object) from NGSI-LD")
         Component(ldo_m, "HTTP out", "Java - **custom** LDI HTTP out", "Sends LDES member (version object)")
    }
}
System_Boundary(pipeline_o, "Observations Pipeline") {
    Container_Boundary(workflow_observations, "IoW Workflow - Observations", "LDI Orchestrator", "Workflow containing standard and custom LDIO components"){
         Component(ldi_o, "HTTP in", "Java - **custom** LDI HTTP in", "Receives NGSI-LD state object")
         Component(creator_o, "LDES member creator", "Java - **custom** LDI translator", "Produces LDES member (version object) from OSLO model")
         Component(translator_o, "NGSI v2 to LD translation", "Java - **custom** LDI translator", "Translates NGSI-v2 to NGSI-LD according to Fiware rules")
         Component(oslo_o, "OSLO translation", "Java - standard LDI translator with **custom** mapping", "Translates NGSI-LD to OSLO model")
         Component(ldo_o, "HTTP out", "Java - **custom** LDI HTTP out", "Sends LDES member (version object)")
    }
}

System(server_observations, "LDES Server Observations", "LDES Server ingesting & serving **WaterQualityObserved**")
System(server_devices, "LDES Server Devices", "LDES Server ingesting & serving **Devices**")
System(server_models, "LDES Server Models", "LDES Server ingesting & serving **DeviceModels**")
System_Ext(database, "Storage", "MongoDB - Contains LDES members and fragments")

Rel_D(tester, ldi_d, "pushes Devices", "HTTPS")
Rel_D(ldi_d, translator_d, "NGSI-v2")
Rel_D(translator_d, creator_d, "NGSI-LD")
Rel_D(creator_d, ldo_d, "LDES member")

Rel_D(tester, ldi_m, "pushes DeviceModels", "HTTPS")
Rel_D(ldi_m, translator_m, "NGSI-v2")
Rel_D(translator_m, creator_m, "NGSI-LD")
Rel_D(creator_m, ldo_m, "LDES member")

Rel_D(generator, ldi_o, "generates and pushes NGSI-v2 updates", "HTTP (method POST)")
Rel_D(ldi_o, translator_o, "NGSI-v2")
Rel_R(translator_o, oslo_o, "NGSI-LD")
Rel_D(oslo_o, creator_o, "OSLO state")
Rel_D(creator_o, ldo_o, "LDES member")

Rel_D(ldo_o, server_observations, "pushes LDES members", "HTTP (method POST)")
Rel_D(ldo_m, server_models, "pushes LDES members", "HTTP (method POST)")
Rel_D(ldo_d, server_devices, "pushes LDES members", "HTTP (method POST)")

Rel_D(server_observations, database, "stores and retrieves LDES members", "mongo")
Rel_D(server_models, database, "stores and retrieves LDES members", "mongo")
Rel_D(server_devices, database, "stores and retrieves LDES members", "mongo")

@enduml
