services:
  ldes-server-simulator:
    image: vsds/ldes-server-simulator
    container_name: template-ldes-server-simulator
    # TODO: use pre-built docker image
    build:
      context: ../../ldes-server-simulator
    ports:
      - "9001:80"
    environment:
      - BASEURL=http://ldes-server-simulator
      - SEED=/tmp/gipod-data
    volumes:
      - ./data/gipod/initial:/tmp/gipod-data:ro
    networks:
      - e2e-test
  ldes-client-workflow:
    image: vsds/ldes-client-workflow
    container_name: template-ldes-client-workflow
    # TODO: use pre-built NAR (NiFi Jar) file & local Docker file
    # instead of relying on LDES client NiFi processor repo 
    # (https://github.com/Informatievlaanderen/VSDS-LDESClient-NifiProcessor)
    build:
      context: ./ldes-client-workflow
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    ports:
      - "8443:8443"
      - "9002:8080"
    volumes:
      - ./nifi/logs:/opt/nifi/nifi-current/logs:rw
      - ./nifi/conf:/opt/nifi/nifi-current/conf:rw
      - ./nifi/flowfile_repository:/opt/nifi/nifi-current/flowfile_repository:rw
    networks:
      - e2e-test
  ldes-client-sink:
    image: vsds/ldes-client-sink
    container_name: template-ldes-client-sink
    # TODO: use pre-built docker image
    build:
      context: ../../ldes-client-sink
    ports:
      - "9003:80"
    networks:
      - e2e-test
networks:
  e2e-test: {}
