# Use case
# USECASE_NAME=workflow

# Workflow compose env vars
LDES_WORKBENCH_NIFI_TAG=
# NIFI_UI_PORT=8443
SINGLE_USER_CREDENTIALS_USERNAME=
SINGLE_USER_CREDENTIALS_PASSWORD=

# NIFI_WORKFLOW_LISTEN_PORT=9010
# NIFI_DATA_FOLDER=./data
