version: '3.3'
services:
  ldes-server:
    env_file:
      - ./ldes-server/config.local.env
    image: ghcr.io/informatievlaanderen/ldes-server:20220704T1516
    ports:
      - "8080:8080"
    networks:
      - ldes
    depends_on:
      - ldes-mongodb
  ldes-mongodb:
    image: mongo
    container_name: ldes.mongodb
    ports:
      - "27017:27017"
    restart: always
    networks:
      - ldes
  ldes-server-simulator:
    image: vsds/ldes-server-simulator
    build:
      context: ../../ldes-server-simulator
    ports:
      - "9001:80"
    environment:
      - BASEURL=http://ldes-server-simulator
      - SEED=/tmp/gipod-data
    volumes:
      - type: bind
        source: ../../ldes-server-simulator/data/gipod
        target: /tmp/gipod-data
    networks:
      - ldes
  replicate-workflow:
    container_name: replicate-workflow
    build:
      context: ./replicate-workflow
      args:
        PAT_READ_PACKAGES: ${PAT_READ_PACKAGES}
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=${SINGLE_USER_CREDENTIALS_USERNAME}
      - SINGLE_USER_CREDENTIALS_PASSWORD=${SINGLE_USER_CREDENTIALS_PASSWORD}
    ports:
      - "8443:8443"
    networks:
      - ldes
networks:
  ldes: {}
