# Workflow compose build args
LDES_CLIENT_NAR_ARTIFACT_ID=
LDES_CLIENT_NAR_VERSION_BASE=
LDES_CLIENT_NAR_VERSION=
LDES_CLIENT_NAR_TAG=
PAT_READ_PACKAGES=

# Workflow compose env vars
NIFI_UI_PORT=8443
SINGLE_USER_CREDENTIALS_USERNAME=
SINGLE_USER_CREDENTIALS_PASSWORD=
