services:
  nifi-workflow:
    image: ${DOCKER_REPO:-ghcr.io/informatievlaanderen}/ldes-workbench-nifi:${LDES_WORKBENCH_NIFI_TAG:-20230214t123440}
    container_name: ${USECASE_NAME:-rdf4j-repository-put}_ldes-workbench-nifi
    environment:
      - NIFI_WEB_HTTP_PORT=${NIFI_UI_PORT:-8000}
    ports:
      - ${NIFI_UI_PORT:-8081}:${NIFI_UI_PORT:-8000}
    networks:
      - ldes
    volumes:
      - "./nifi:/home/nifi/data"
  rdf4j-server:
    image: eclipse/rdf4j-workbench:${RDF4J_SERVER_TAG:-4.2.2}
    container_name: ${USECASE_NAME:-rdf4j-repository-put}_rdf4j-server
    environment:
      - "JAVA_OPTS=-Xms1g -Xmx4g"
    ports:
      - 8080:8080
    networks:
      - ldes
networks:
  ldes:
    name: ${USECASE_NAME:-rdf4j-repository-put}_network
