server:
  port: 8080
orchestrator:
  input:
    name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpIn
  transformers:
    - name: be.vlaanderen.informatievlaanderen.ldes.ldi.VersionObjectCreator
      config:
        member-type: https://uri.etsi.org/ngsi-ld/default-context/DeviceModel
        delimiter: "/"
        date-observed-property: ""
        generatedAt-property: http://www.w3.org/ns/prov#generatedAtTime
        versionOf-property: http://purl.org/dc/terms/isVersionOf
  outputs:
    - name: be.vlaanderen.informatievlaanderen.ldes.ldio.LdioHttpOut
      config:
        endpoint: http://ldes-server-models:8080/device-models
        content-type: application/n-quads
