# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 1. Build LDES list fragments

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    paths:
    - 'ldes-list-fragments/**'
    - .github/workflows/pr-build.ldes-list-fragments.yml

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ldes-list-fragments

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
   
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install dependencies
      run: npm ci
      
    - name: Dependency Check
      uses: dependency-check/Dependency-Check_Action@1.1.0
      id: Depcheck
      with:
        project: LDES list fragments
        path: ./ldes-list-fragments
        format: HTML

    - name: Upload Test results
      uses: actions/upload-artifact@v3
      with:
        name: Depcheck report ldes-list-fragments-${{ matrix.node-version }}
        path: ${{ github.workspace }}/reports/
    
    - name: Build
      run: npm run build
