name: Run Cypress Tests

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  run-test:
    strategy:
      fail-fast: false
      matrix:
        tags:
          - "@test-001"
          - "@test-003"
          - "@test-007"
          - "@test-014"
          - "@test-017"
          - "@test-018"
          - "@test-019 and @consumption and @cacheability"
          - "@test-019 and @consumption and @compression"
          - "@test-019 and @consumption and @caching"
          - "@test-020"
          # - Disabled for since mongock upgrade is no longer relevant. Liquibase approach needs to be discussed
          # - "@test-021"
          - "@test-024"
          - "@test-026"
          - "@test-031"
          - "@test-032"
          - "@test-034"
          - "@test-035"
          - "@test-037"
          - "@test-038"
          # - "@test-039" BROKEN!
          - "@test-040"

    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialize Test Context
        run: sudo ./init-test-context.sh
        shell: bash

      - name: Test
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_TAGS: ${{ matrix.tags }}
      
      - name: Log Running Container Logs
        if: '!cancelled()'
        run: ./log-running-containers.sh
        shell: bash

