name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      integration-tests: ${{ steps.parse.outputs.integration-tests }}
      component-tests: ${{ steps.parse.outputs.component-tests }}
      
    steps:
      - name: Free disk space
        run:
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        shell: bash
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest images
        run: ./get-latest-docker-images.sh
        shell: bash

      - name: Test
        uses: cypress-io/github-action@v5
        env:
          CYPRESS_TAGS: not (@broken)
