name: Cypress Tests

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    outputs:
      integration-tests: ${{ steps.parse.outputs.integration-tests }}
      component-tests: ${{ steps.parse.outputs.component-tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        uses: cypress-io/github-action@v5
        start: npm run test