name: Cypress Tests

on:
  push:
    branches:
      - 'feat/gh-action-automation'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          build: |
            ls
            ls ..
            get-previous-docker-images.sh
            npm install
          start: npm test